#docker-compose.yml: describes container build, config, and connections.
services:

#PostgreSQL container.
  db:
    image: postgres:17
    container_name: bluepeak-db
    restart: always
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

#Node.js container.
  backend:
    build: .
    container_name: bluepeak-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user123
      DB_PASSWORD: password123
      DB_NAME: db123
      NODE_ENV: development
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

volumes:
#Stores PostgreSQL data files persistentlty outside the continer filesystem
  db_data:
